name: 'pytest report handler'
description: 'Save pytest report (junit) to GHA Artifacts'
inputs:
  action:
    description: "The action to take with the report (download / upload)"
    default: download
    required: true
  artifact:
    description: "The artifact name that will be used when uploading to GHA"
    default: pytest-report
    required: true
  branch:
    description: "The main branch"
    default: master
    required: true
  path:
    description: "The download path for reports"
    default: '.pytest-reference-reports'
    required: true
  src:
    description: "The report to upload. This will need to be renamed"
    required: true
  dest:
    description: "The report name that will be saved to GHA Artifacts. This is different due to test runners with multiple instances where we do not want it to overwrite."
    required: true

runs:
  using: "composite"
  steps:
    # Will be empty for non pull requests
    - id: 'current-branch'
      shell: bash
      run: echo "::set-output name=name::$(echo ${GITHUB_HEAD_REF#refs/heads/})"

    - name: Fetch existing report from master
      if: inputs.action != 'upload'
      id: 'get-artifact'
      uses: getsentry/action-download-workflow-artifact@2c7fdc458e9fb008b94b8399a483ff6e3af883b1
      with:
        branch: ${{ inputs.branch }}
        artifact: ${{ inputs.artifact }}
        path: ${{ github.workspace }}/${{ inputs.path }}
        workflowEvent: pull_request # temp for artifacts on branch

    # Overwrite reports from master if branch reports exist
    #
    # Note branch reports are also from master, but this way a branch will
    # always use the same report instead of fetching latest from master.
    - name: Fetch report from current branch (if not master)
      if: inputs.action != 'upload' && steps.current-branch.outputs.name != ''
      id: 'get-artifact-branch'
      uses: getsentry/action-download-workflow-artifact@2c7fdc458e9fb008b94b8399a483ff6e3af883b1
      with:
        branch: ${{ steps.current-branch.outputs.name }}
        artifact: ${{ inputs.artifact }}__internal
        path: ${{ github.workspace }}/${{ inputs.path }}
        ignoreError: true
        workflowEvent: pull_request
        # workflowEvent: push

    - name: Debug
      shell: bash
      run: |
        echo '${{ steps.get-artifact.outcome }}'
        echo '${{ steps.get-artifact.conclusion }}'

    # This is temp as `steps.<id>.outcome` is broken right now
    - name: Does artifact exist
      if: inputs.action != 'upload'
      id: artifact-exists
      shell: bash
      run: |
        test -f ${{ inputs.dest }} && echo "::set-output name=exists::1"


    # We re-upload the report that was from the master branch so that the same
    # report is always used within a PR.
    # This is so the test order remains consistent a PR.
    - name: Upload report for branch
      # Ideally we'd use the below check
      # if: steps.get-artifact.outcome == 'success'
      if: inputs.action != 'upload' && steps.artifact-exists.outputs.exists == '1'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact }}__internal
        path: ${{ inputs.dest }}

    # Need to rename so if we have multiple test instances, the reports do not overwrite each other on GHA
    - name: Rename report
      if: inputs.action == 'upload'
      shell: bash
      run: mv ${{ inputs.src }} ${{ inputs.dest }}

    - name: Upload report
      if: inputs.action == 'upload'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact }}
        path: ${{ inputs.dest }}
