name: 'pytest report handler'
description: 'Save pytest report (junit) to GHA Artifacts'
inputs:
  action:
    description: "The action to take with the report (download / upload)"
    default: download
    required: true
  src:
    description: "The report to upload. This will need to be renamed"
    required: true
  dest:
    description: "The report name that will be saved to GHA Artifacts. This is different due to test runners with multiple instances where we do not want it to overwrite."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: mkdir .pytest_report

    - name: Download report
      if: inputs.action != 'upload'
      uses: actions/download-artifact@v2
      with:
        name: pytest-report
        path: .pytest_report

    # Need to rename so if we have multiple test instances, the reports do not overwrite each other
    - name: Rename report
      if: inputs.action == 'upload'
      shell: bash
      run: mv ${{ inputs.src }} ${{ inputs.dest }}

    - name: Upload report
      if: inputs.action == 'upload'
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: ${{ inputs.dest }}
