name: 'pytest report handler'
description: 'Save pytest report (junit) to GHA Artifacts'
inputs:
  action:
    description: "The action to take with the report (download / upload)"
    default: download
    required: true
  artifact:
    description: "The artifact name that will be used when uploading to GHA"
    default: pytest-report
    required: true
  branch:
    description: "The main branch"
    default: master
    required: true
  path:
    description: "The download path for reports"
    default: '.pytest-reference-reports'
    required: true
  src:
    description: "The report to upload. This will need to be renamed"
    required: true
  dest:
    description: "The report name that will be saved to GHA Artifacts. This is different due to test runners with multiple instances where we do not want it to overwrite."
    required: true

runs:
  using: "composite"
  steps:
    - name: Get report artifact URL
      if: inputs.action != 'upload'
      id: 'get-artifact'
      uses: getsentry/action-download-workflow-artifact@v0
      with:
        branch: ${{ inputs.branch }}
        artifact: ${{ inputs.artifact }}
        path: ${{ github.workspace }}/${{ inputs.path }}

    - name: Debug
      if: inputs.action != 'upload'
      shell: bash
      run: |
        ls ${{ github.workspace }}/${{ inputs.path }}
        echo $(pwd)

    # Need to rename so if we have multiple test instances, the reports do not overwrite each other
    - name: Rename report
      if: inputs.action == 'upload'
      shell: bash
      run: mv ${{ inputs.src }} ${{ inputs.dest }}

    - name: Upload rport
      if: inputs.action == 'upload'
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: ${{ inputs.dest }}
