name: Enforce License Compliance

on:
  pull_request:
    branches: [master, main]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@994645d241ac1992c8f84ba4470664f55abf481d  # main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
