name: Enforce License Compliance

on:
  pull_request:
    branches: [master, main]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@67115e57fad9fd1deca27045a49617f8214fed7a  # main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
