name: pull transifex
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1,15 * *'

jobs:
  pull-transifex:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
        name: Checkout sentry

      - uses: getsentry/action-setup-volta@54775a59c41065f54ecc76d1dd5f2cdc7a1550cb # v1.1.0

      - run: sudo apt-get install -y gettext

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup sentry python env
        uses: ./.github/actions/setup-sentry
        id: setup

      - name: Pull from Transifex
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          SENTRY_NO_VENV_CHECK: 1
        run: |
          make pull-transifex
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # v4.2.0
        with:
          token: ${{ secrets.BUMP_SENTRY_TOKEN }}
          add-paths: |
            src/sentry/locale
          commit-message: 'meta(i18n): Update translations'
          branch: 'meta/i18n/auto-update-translations'
          reviewers: ${{ github.triggering_actor }}
          team-reviewers: |
            getsentry/app-frontend
          delete-branch: true
          base: master
          title: 'meta(i18n): Update translations'
          body: |
            This PR was auto-generated - it updates translations from Transifex
