name: transifex
on:
  pull_request:
  workflow_dispatch:

jobs:
  pull-transifex:
    name: pull from transifex
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
        name: Checkout sentry

      - run: sudo apt-get install -y gettext

      - name: Setup sentry python env
        uses: ./.github/actions/setup-sentry
        id: setup

      - name: Pull from Transifex
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          SENTRY_NO_VENV_CHECK: 1
        run: |
          make update-locale-locales
          git status

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # v4.2.0
      #   with:
      #     token: ${{ secrets.BUMP_SENTRY_TOKEN }}
      #     add-paths: |
      #       src/sentry/locale
      #     commit-message: 'meta(i18n): Update translated message files'
      #     branch: 'meta/i18n/auto-update-translations'
      #     reviewers: ${{ github.triggering_actor }}
      #     team-reviewers: |
      #       getsentry/app-frontend
      #     delete-branch: true
      #     base: master
      #     title: 'meta(i18n): Update translated message files'
      #     body: |
      #       This PR was auto-generated - it updates translations from Transifex
