name: push transifex
on:
  # pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1,15 * *'
jobs:
  jest-balance:
    # Buckle up, this may take a while
    timeout-minutes: 60
    # Make sure this matches the runner that runs frontend tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
        name: Checkout sentry

      - uses: getsentry/action-setup-volta@54775a59c41065f54ecc76d1dd5f2cdc7a1550cb # v1.1.0

      - run: sudo apt-get install -y gettext

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Setup sentry python env
        uses: ./.github/actions/setup-sentry
        id: setup

      - name: Push to Transifex
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          SENTRY_NO_VENV_CHECK: 1
        run: make push-transifex
